// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wuddyeecktmhywklpusr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind1ZGR5ZWVja3RtaHl3a2xwdXNyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMDk0MjYsImV4cCI6MjA2NTU4NTQyNn0.W7BGabGp6uefp5KOONshSHODGuyjPDfguOAeyPi2xeg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);